x = input('enter a key: ')
print('Your key is a letter?', x.isalpha())
print('Your key is upper?', x.isupper())
print('Your key is lower?', x.islower())
print('Your key is a number?', x.isnumeric())
print('You key is a letter and number?', x.isalnum())
print('Your key is a ?', x.isascii())
print('Your key is a complex? ')
print('Your key is a boolean? ')
print('Your key is a string? ')