x = int(input('insira um valor: '))
print(f'A tabuada de multiplicação de {x} é:')
print('='*10)
print(f'{x}x1 = {x*1}\n{x}x2 = {x*2}\n{x}x3 = {x*3}\n{x}x4 = {x*4}\n{x}x5 = {x*5}\n{x}x6 = {x*6}\n{x}x7 = {x*7}\n{x}x8 = {x*8}\n{x}x9 = {x*9}')
print('='*10)
