x = input('Digite algo: ')
print(x.capitalize())
print('O tipo primitivo é', type(x))
print('Tem apenas espaços?', x.isspace())
print('É número?', x.isnumeric())
print('É letra?', x.isalpha())
print('É alfanumérico?', x.isalnum())
print('Está em maiúsculas?', x.isupper())
print('Está em minúsculas?', x.islower())
print('Está capitalizada?', x.istitle())
